server:
  port: 8084
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/taotao?characterEncoding=utf8&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    timeout: 100ms
    password: 123456


mybatis:
  mapper-locations: classpath:/mappers/*
  type-aliases-package: com.taotao.pojo
  #开启mybatis中自动映射成小驼峰
  configuration:
    map-underscore-to-camel-case: true

taotao:
  redis:
    login:
      token:
        prefix: TAOTAO_USER_TOKEN