server:
  port: 8081
spring:
  datasource:
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/taotao?characterEncoding=utf8&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    servlet:
      path: /rest
  redis:
    host: www.taotao.com
    jedis:
      pool:
        max-idle: 2
        max-wait: 1000ms

mybatis:
  mapper-locations: classpath:/mappers/*
  type-aliases-package: com.taotao.pojo

logging:
  level:
    root: info
    com.taotao.mapper: debug
dubbo:
  application:
    name: rest-provider
    qos-enable: false

  protocol:
    name: dubbo
    host: 10.10.14.189
    port: 20880

  registry:
    address: zookeeper://10.10.14.125:3181?backup=10.10.14.125:3182,10.10.14.125:3183
